CLIENT_TOOL=busybox-udhcpc
EXPECT_RESULT=lease
EXPECT_IP_RANGE=192.168.1.100-192.168.1.200
EXPECT_ROUTER=192.168.1.1
EXPECT_DNS=192.168.1.1
EXPECT_LEASE_TIME=43200
EXPECT_DOMAIN=example.test
EXPECT_NTP=192.168.1.1
